### ISSUE TITLE
ServerAuth/Login not work.

### ISSUE THREAD

**Issue by kukkarn** [H4PM/Elywing#336] opened 2017-01-07 08:21 UTC
I'm have a update latest version Elywing (07/01/2017)
My plugin ServerAuth or login not work

How to fix this problem?
Thank.. 😊

**Comment by SuperMaXAleX** [comment] 2017-01-07 09:02
No precision. No informations. No code.

**Comment by Xelcronia** [comment] 2017-01-07 09:20
Must be #320

**Comment by thebigsmileXD** [comment] 2017-01-07 09:58
Duplicate of #320

**Closed by thebigsmileXD** 2017-01-07 09:58 UTC
