### ISSUE TITLE
DUPLICATION BUG

### ISSUE THREAD

**Issue by daniktheboss** [H4PM/Elywing#98] opened 2016-11-08 05:44 UTC
So people can duplicate items in survival mode using only chests. They take the item from chest and when they close it, it drops another pair. Or maybe it's hoppers... please fix asap

**Comment by SuperMaXAleX** [comment] 2016-11-08 06:48
No problem.

**Comment by TDMidkwhatisxd** [comment] 2016-11-08 07:44
Hoopers are fixed!

**Comment by daniktheboss** [comment] 2016-11-09 08:15
-_- they duplicate emerald keys....

**Comment by TDMidkwhatisxd** [comment] 2016-11-09 08:17
Are u using Elywing? If so , latest one? Give me your sv ip!
There was a glich with hopper , but is fixed!

**Comment by daniktheboss** [comment] 2016-11-09 08:19
Haha your funny. I'm not giving my public ip on github. Also, if you think in a noob and don't know stuff, please go learn. I tried everything to prevent the duplication glitch but, pocketmine is pocketmine. So, this is a bug.

**Comment by TDMidkwhatisxd** [comment] 2016-11-09 08:23
@SuperMaXAleX  he is a troller please close the issue, not even a way to reproduce!
Im out, i forked this build! I will continue it, and trolls like u will be banned!

**Comment by daniktheboss** [comment] 2016-11-09 08:25
😂 well developers like me won't want to see such ugly code you will wrote. Anyways the player duplicated so it is reproducible.

**Comment by TDMidkwhatisxd** [comment] 2016-11-09 08:26
@SuperMaXAleX  if u make this a plugin, i will continue it as a fork for my sv!

**Comment by TDMidkwhatisxd** [comment] 2016-11-09 08:27
@daniktheboss  you are not a dev. Get lost! I cant reproduce your issue!

**Comment by daniktheboss** [comment] 2016-11-09 08:27
Everyone note "fork"

**Comment by daniktheboss** [comment] 2016-11-09 08:28
Also, please define troller to me

**Comment by TDMidkwhatisxd** [comment] 2016-11-09 08:28
Forgot to unsubscribe

**Comment by Aericio** [comment] 2016-11-09 08:47
> fork

More like a spoon

**Comment by Aericio** [comment] 2016-11-09 08:49
Any chance you could speak better english?

**Comment by daniktheboss** [comment] 2016-11-09 15:35
Well haha who said I aint? Who is partially continuing bytecraft? ME what plugins did you write? NOOB please just stop making yourself look smarter by saying "give me your ip" or "not reproducable"

**Closed** 2016-12-01 17:16 UTC
Labels: bug
