### ISSUE TITLE
Suggestion. 

### ISSUE THREAD

**Issue by Tolo0** [H4PM/Elywing#383] opened 2017-01-12 08:16 UTC
Wouldn't it make sense to create 2 official Elywing Branches.
 1 that is in beta for testing all the new commits. 
Then 1 that is stable for commercial use.  
Theys so many devs contributing and adding there progress to Elywing before properly testing it out. This is making Elywing so unstable. Iv had to downgrade to a older version of Elywing and I'm scared to update it again lol. 
All you guys are doing a great job. Some of you just need to be abit more organised.

**Comment by thebigsmileXD** [comment] 2017-01-12 08:51
Duplicate of https://github.com/H4PM/Elywing/issues/359

**Closed by thebigsmileXD** 2017-01-12 08:51 UTC
