### ISSUE TITLE
Some plugins wont load

### ISSUE THREAD

**Issue by ItzWalla** [H4PM/Elywing#339] opened 2017-01-07 09:23 UTC
After y'all updated your server software a couple minutes ago, this happened. All plugins were working perfectly fine before I upated a couple minutes ago,

IMAGE: (https://cloud.githubusercontent.com/assets/20291307/21740758/ce9c296e-d477-11e6-9b40-ff75ebb357c0.PNG)

**Comment by thebigsmileXD** [comment] 2017-01-07 09:59
Duplicate of #336

**Closed by thebigsmileXD** 2017-01-07 09:59 UTC
