### ISSUE TITLE
Level bug

### ISSUE THREAD

**Issue by gigantessbeta** [H4PM/Elywing#155] opened 2016-12-24 01:28 UTC
When loading the flat world,
The terrain becomes strange

**Comment by thebigsmileXD** [comment] 2016-12-24 06:48
I confirm

**Comment by thebigsmileXD** [comment] 2016-12-24 06:49
Duplicate of #152

**Comment by SuperMaXAleX** [comment] 2016-12-24 07:01
I have this issue to. Maybe it's coming from MCRegion.

**Closed** 2016-12-31 11:02 UTC
Labels: bug

**Comment by thebigsmileXD** [comment] 2016-12-31 14:15
This should be solved when i pr the changes over.
